CREATE DATABASE elementsapi;

\c elementsapi

CREATE TABLE elements (
    name VARCHAR(255),
    symbol VARCHAR(255),
    atomic_number INT PRIMARY KEY,
    atomic_mass REAL,
    standard_state VARCHAR(255),
    melting_point REAL,
    boiling_point REAL,
    subcategory VARCHAR(255),
    year_discovered INT
);

INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Hydrogen', 'H', 1, 1.0080, 'Gas', 13.81, 20.28, 'Nonmetal', 1766);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Helium', 'He', 2, 4.00260, 'Gas', 0.95, 4.22, 'Noble Gas', 1868);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Lithium', 'Li', 3, 7.0, 'Solid', 453.65, 1615, 'Alkali Metal', 1817);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Beryllium', 'Be', 4, 9.012183, 'Solid', 1560, 2744, 'Alkaline Earth Metal', 1798);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Boron', 'B', 5, 10.81, 'Solid', 2348, 4273, 'Metalloid', 1808);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Carbon', 'C', 6, 12.011, 'Solid', 3823, 4098, 'Nonmetal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Nitrogen', 'N', 7, 14.007, 'Gas', 63.15, 77.36, 'Nonmetal', 1772);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Oxygen', 'O', 8, 15.999, 'Gas', 54.36, 90.2, 'Nonmetal', 1774);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Fluorine', 'F', 9, 18.99840316, 'Gas', 53.53, 85.03, 'Halogen', 1670);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Neon', 'Ne', 10, 20.180, 'Gas', 24.56, 27.07, 'Noble Gas', 1898);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Sodium', 'Na', 11, 22.9897693, 'Solid', 370.95, 1156, 'Alkali Metal', 1807);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Magnesium', 'Mg', 12, 24.305, 'Solid', 923, 1363, 'Alkaline Earth Metal', 1808);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Aluminum', 'Al', 13, 26.981538, 'Solid', 933.437, 2792, 'Post-Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Silicon', 'Si', 14, 28.085, 'Solid', 1687, 3538, 'Metalloid', 1854);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Phosphorus', 'P', 15, 30.97376200, 'Nonmetal', 317.3, 553.65, 'Nonmetal', 1669);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Sulfur', 'S', 16, 32.07, 'Solid', 388.36, 717.75, 'Nonmetal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Chlorine', 'Cl', 17, 34.45, 'Gas', 171.65, 239.11, 'Halogen', 1774);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Argon', 'Ar', 18, 39.9, 'Gas', 83.8, 87.3, 'Noble Gas', 1894);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Potassium', 'K', 19, 39.0983, 'Solid', 336.53, 1032, 'Alkali Metal', 1807);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Calcium', 'Ca', 20, 40.078, 'Solid', 1115, 1757, 'Alkaline Earth Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Scandium', 'Sc', 21, 44.955908, 'Solid', 1814, 3109, 'Transition Metal', 1879);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Titanium', 'Ti', 22, 47.867, 'Solid', 1941, 3560, 'Transition Metal', 1791);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Vanadium', 'V', 23, 50.9415, 'Solid', 2183, 3680, 'Transition Metal', 1801);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Chromium', 'Cr', 24, 51.9961, 'Solid', 2180, 2944, 'Transition Metal', 1797);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Manganese', 'Mn', 25, 54.938045, 'Solid', 1519, 2334, 'Transition Metal', 1774);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Iron', 'Fe', 26, 55.845, 'Solid', 1811, 3134, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Cobalt', 'Co', 27, 58.933194, 'Solid', 1768, 3200, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Nickel', 'Ni', 28, 58.6934, 'Solid', 1728, 3186, 'Transition Metal', 1751);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Copper', 'Cu', 29, 63.546, 'Solid', 1357.77, 2835, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Zinc', 'Zn', 30, 65.38, 'Solid', 692.68, 1180, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Gallium', 'Ga', 31, 69.723, 'Solid', 302.9146, 2477, 'Post-Transition Metal', 1875);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Germanium', 'Ge', 32, 72.63, 'Solid', 1211.4, 3106, 'Metalloid', 1886);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Arsenic', 'As', 33, 74.921595, 'Solid', 1090, 887, 'Metalloid', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Selenium', 'Se', 34, 78.971, 'Solid', 453, 958, 'Nonmetal', 1817);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Bromine', 'Br', 35, 79.904, 'Liquid', 265.8, 332.0, 'Halogen', 1826);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Krypton', 'Kr', 36, 83.798, 'Gas', 115.79, 119.93, 'Noble Gas', 1898);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Rubidium', 'Rb', 37, 85.4678, 'Solid', 312.46, 961, 'Alkali Metal', 1861);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Strontium', 'Sr', 38, 87.62, 'Solid', 1050, 1655, 'Alkaline Earth Metal', 1790);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Yttrium', 'Y', 39, 88.90584, 'Solid', 1799, 3609, 'Transition Metal', 1794);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Zirconium', 'Zr', 40, 91.224, 'Solid', 2128, 4682, 'Transition Metal', 1789);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Niobium', 'Nb', 41, 92.90637, 'Solid', 2750, 5017, 'Transition Metal', 1801);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Molybdenum', 'Mo', 42, 95.95, 'Solid', 2896, 4912, 'Transition Metal', 1778);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Technetium', 'Tc', 43, 98, 'Solid', 2430, 4538, 'Transition Metal', 1937);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Ruthenium', 'Ru', 44, 101.07, 'Solid', 2607, 4423, 'Transition Metal', 1844);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Rhodium', 'Rh', 45, 102.90550, 'Solid', 2237, 3968, 'Transition Metal', 1803);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Palladium', 'Pd', 46, 106.42, 'Solid', 1828.05, 3236, 'Transition Metal', 1803);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Silver', 'Ag', 47, 107.8682, 'Solid', 1234.93, 2435, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Cadmium', 'Cd', 48, 112.414, 'Solid', 594.22, 1040, 'Transition Metal', 1817);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Indium', 'In', 49, 114.818, 'Solid', 429.75, 2345, 'Post-Transition Metal', 1863);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Tin', 'Sn', 50, 118.710, 'Solid', 505.08, 2875, 'Post-Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Antimony', 'Sb', 51, 121.760, 'Solid', 903.78, 1860, 'Metalloid', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Tellurium', 'Te', 52, 127.60, 'Solid', 722.66, 1261, 'Metalloid', 1782);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Iodine', 'I', 53, 126.90447, 'Solid', 386.85, 457.4, 'Halogen', 1811);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Xenon', 'Xe', 54, 131.293, 'Gas', 161.4, 165.03, 'Noble Gas', 1898);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Cesium', 'Cs', 55, 132.90545196, 'Solid', 301.59, 944, 'Alkali Metal', 1860);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Barium', 'Ba', 56, 137.327, 'Solid', 1000, 2170, 'Alkaline Earth Metal', 1808);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Lanthanum', 'La', 57, 138.90547, 'Solid', 1193, 3737, 'Lanthanide', 1839);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Cerium', 'Ce', 58, 140.116, 'Solid', 1068, 3426, 'Lanthanide', 1803);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Praseodymium', 'Pr', 59, 140.90766, 'Solid', 1208, 3793, 'Lanthanide', 1885);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Neodymium', 'Nd', 60, 144.242, 'Solid', 1297, 3347, 'Lanthanide', 1885);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Promethium', 'Pm', 61, 145, 'Solid', 1315, 3273, 'Lanthanide', 1945);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Samarium', 'Sm', 62, 150.36, 'Solid', 1345, 2067, 'Lanthanide', 1879);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Europium', 'Eu', 63, 151.964, 'Solid', 1099, 1802, 'Lanthanide', 1901);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Gadolinium', 'Gd', 64, 157.25, 'Solid', 1585, 3546, 'Lanthanide', 1880);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Terbium', 'Tb', 65, 158.92535, 'Solid', 1629, 3503, 'Lanthanide', 1843);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Dysprosium', 'Dy', 66, 162.500, 'Solid', 1680, 2840, 'Lanthanide', 1886);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Holmium', 'Ho', 67, 164.93033, 'Solid', 1734, 2873, 'Lanthanide', 1878);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Erbium', 'Er', 68, 167.259, 'Solid', 1802, 3141, 'Lanthanide', 1842);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Thulium', 'Tm', 69, 168.93422, 'Solid', 1818, 2223, 'Lanthanide', 1879);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Ytterbium', 'Yb', 70, 173.045, 'Solid', 1097, 1469, 'Lanthanide', 1878);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Lutetium', 'Lu', 71, 174.9668, 'Solid', 1925, 3675, 'Lanthanide', 1907);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Hafnium', 'Hf', 72, 178.49, 'Solid', 2506, 4876, 'Transition Metal', 1923);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Tantalum', 'Ta', 73, 180.94788, 'Solid', 3290, 5731, 'Transition Metal', 1802);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Tungsten', 'W', 74, 183.84, 'Solid', 3695, 6203, 'Transition Metal', 1783);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Rhenium', 'Re', 75, 186.207, 'Solid', 3459, 5903, 'Transition Metal', 1925);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Osmium', 'Os', 76, 190.23, 'Solid', 3306, 5285, 'Transition Metal', 1803);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Iridium', 'Ir', 77, 192.217, 'Solid', 2719, 4701, 'Transition Metal', 1803);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Platinum', 'Pt', 78, 195.084, 'Solid', 2041.4, 4098, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Gold', 'Au', 79, 196.966569, 'Solid', 1337.33, 3243, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Mercury', 'Hg', 80, 200.592, 'Liquid', 234.32, 629.88, 'Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Thallium', 'Tl', 81, 204.38, 'Solid', 577, 1746, 'Post-Transition Metal', 1861);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Lead', 'Pb', 82, 207.2, 'Solid', 600.61, 2022, 'Post-Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Bismuth', 'Bi', 83, 208.98040, 'Solid', 544.7, 1837, 'Post-Transition Metal', -1); -- Element has been known since ancient times and does not have a recorded year of discovery
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Polonium', 'Po', 84, 209, 'Solid', 527, 1235, 'Metalloid', 1898);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Astatine', 'At', 85, 210, 'Solid', 575, 610, 'Halogen', 1940);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Radon', 'Rn', 86, 222, 'Gas', 202, 211.3, 'Noble Gas', 1900);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Francium', 'Fr', 87, 223, 'Solid', 300, 950, 'Alkali Metal', 1939);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Radium', 'Ra', 88, 226, 'Solid', 973, 2010, 'Alkaline Earth Metal', 1898);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Actinium', 'Ac', 89, 227, 'Solid', 1323, 3471, 'Actinide', 1899);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Thorium', 'Th', 90, 232.0377, 'Solid', 2115, 5061, 'Actinide', 1829);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Protactinium', 'Pa', 91, 231.03588, 'Solid', 1841, 4300, 'Actinide', 1913);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Uranium', 'U', 92, 238.02891, 'Solid', 1405.3, 4404, 'Actinide', 1789);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Neptunium', 'Np', 93, 237, 'Solid', 917, 4273, 'Actinide', 1940);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Plutonium', 'Pu', 94, 244, 'Solid', 912.5, 3501, 'Actinide', 1940);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Americium', 'Am', 95, 243, 'Solid', 1449, 2880, 'Actinide', 1944);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Curium', 'Cm', 96, 247, 'Solid', 1613, 3400, 'Actinide', 1944);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Berkelium', 'Bk', 97, 247, 'Solid', 1259, 2900, 'Actinide', 1949);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Californium', 'Cf', 98, 251, 'Solid', 1173, 1743, 'Actinide', 1950);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Einsteinium', 'Es', 99, 252, 'Solid', 1133, 1269, 'Actinide', 1952);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Fermium', 'Fm', 100, 257, 'Solid', 1800, -1, 'Actinide', 1952);  -- Boiling point not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Mendelevium', 'Md', 101, 258, 'Solid', 1100, -1, 'Actinide', 1955); -- Boiling point not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Nobelium', 'No', 102, 259, 'Solid', 1100, -1, 'Actinide', 1957); -- Boiling point not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Lawrencium', 'Lr', 103, 266, 'Solid', 1900, -1, 'Actinide', 1961);  -- Boiling point not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Rutherfordium', 'Rf', 104, 267, 'Solid', 2400, 5800, 'Transition Metal', 1964);
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Dubnium', 'Db', 105, 268, 'Solid', -1, -1, 'Transition Metal', 1967); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Seaborgium', 'Sg', 106, 269, 'Solid', -1, -1, 'Transition Metal', 1974); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Bohrium', 'Bh', 107, 270, 'Solid', -1, -1, 'Transition Metal', 1981); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Hassium', 'Hs', 108, 269, 'Solid', -1, -1, 'Transition Metal', 1984); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Meitnerium', 'Mt', 109, 278, 'Unknown', -1, -1, 'Unknown', 1982); -- State, melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Darmstadtium', 'Ds', 110, 281, 'Unknown', -1, -1, 'Unknown', 1994); -- State, melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Roentgenium', 'Rg', 111, 282, 'Unknown', -1, -1, 'Unknown', 1994); -- State, melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Copernicium', 'Cn', 112, 285, 'Gas', -1, -1, 'Transition Metal', 1996); -- State, melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Nihonium', 'Nh', 113, 286, 'Solid', -1, -1, 'Post-Transition Metal', 2003); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Flerovium', 'Fl', 114, 289, 'Solid', -1, -1, 'Post-Transition Metal', 1998); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Moscovium', 'Mc', 115, 290, 'Solid', -1, -1, 'Post-Transition Metal', 2003); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Livermorium', 'Lv', 116, 293, 'Solid', -1, -1, 'Post-Transition Metal', 2000); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Tennessine', 'Ts', 117, 294, 'Solid', -1, -1, 'Halogen', 2010); -- Melting and boiling points not well established
INSERT INTO elements (name, symbol, atomic_number, atomic_mass, standard_state, melting_point, boiling_point, subcategory, year_discovered) VALUES ('Oganesson', 'Og', 118, 294, 'Gas', -1, -1, 'Noble Gas', 2002); -- Melting and boiling points not well established
